apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dashboard.consul.io
    http:
      paths:
      - backend:
          serviceName: dashboard-service
          servicePort: 9002
        path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webconsole
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webconsole.consul.io
    http:
      paths:
      - backend:
          serviceName: consul-consul-ui
          servicePort: 80
        path: /
